package ru.dmt100.flight_booking.sql.enums;

import ru.dmt100.flight_booking.sql.Query;

public enum GeneralSqlQuery implements Query {
    DROP_BOARDING_PASSES_FLIGHT_ID_SEAT_NO_UNIQUE("DROP_BOARDING_PASSES_FLIGHT_ID_SEAT_NO_UNIQUE"),
    ADD_BOARDING_PASSES_UNIQUE_CONSTRAINT("ADD_BOARDING_PASSES_UNIQUE_CONSTRAINT"),
    DROP_TICKETS_BOOK_REF_FKEY("DROP_TICKETS_BOOK_REF_FKEY"),
    ADD_TICKETS_BOOK_REF_FKEY("ADD_TICKETS_BOOK_REF_FKEY"),
    DROP_TICKET_FLIGHTS_TICKET_NO_FKEY("DROP_TICKET_FLIGHTS_TICKET_NO_FKEY"),
    ADD_TICKET_FLIGHTS_TICKET_NO_FKEY("ADD_TICKET_FLIGHTS_TICKET_NO_FKEY"),
    DROP_BOARDING_PASSES_TICKET_NO_FKEY("DROP_BOARDING_PASSES_TICKET_NO_FKEY"),
    ADD_BOARDING_PASSES_TICKET_NO_FKEY("ADD_BOARDING_PASSES_TICKET_NO_FKEY"),
    AIRPORT_BY_CODE("AIRPORT_BY_CODE"),
    AIRCRAFT_BY_CODE("AIRCRAFT_BY_CODE");

    private final String queryKey;

    GeneralSqlQuery(String queryKey) {
        this.queryKey = queryKey;
    }

    @Override
    public String getQuery(String query) {
        return queryKey;
    }
}
